import type { Cooperative, ServiceItem, WorkerItem, JobItem, AllocationEvaluation, ForecastResponse, InstitutionalProject } from './api';

export const MOCK_COOPERATIVES: Cooperative[] = [
  {
    id: 1,
    name: 'Delhi Labour & Construction Cooperative Society',
    registration_id: 'DL-COO-2018-0492',
    state: 'Delhi',
    district: 'Central Delhi',
    address: 'Plot 14, Pusa Road, Karol Bagh, New Delhi',
    contact_phone: '+91 11 2578 9012',
    contact_email: 'contact@delhilabourcoop.in',
    type: 'Labour & Construction',
    verification_status: 'VERIFIED',
    service_categories: ['Electrical', 'Plumbing', 'Carpentry', 'Painting', 'Masonry'],
    commission_rate: 0.15,
    welfare_contribution_rate: 0.05,
    total_members: 64,
    total_jobs_completed: 412,
    welfare_fund_pool: 284500,
  },
  {
    id: 2,
    name: 'Shramik Seva Cooperative Union',
    registration_id: 'DL-COO-2019-1108',
    state: 'Delhi',
    district: 'South Delhi',
    address: '32, Community Centre, Saket, New Delhi',
    contact_phone: '+91 11 2956 3341',
    contact_email: 'info@shramikseva.org',
    type: 'Multi-Service Labour',
    verification_status: 'VERIFIED',
    service_categories: ['Electrical', 'Plumbing', 'HVAC / AC Repair', 'Appliance Repair'],
    commission_rate: 0.15,
    welfare_contribution_rate: 0.05,
    total_members: 48,
    total_jobs_completed: 318,
    welfare_fund_pool: 198200,
  },
  {
    id: 3,
    name: 'NCR Karigar Mahila Cooperative',
    registration_id: 'HR-COO-2020-0382',
    state: 'Haryana',
    district: 'Gurugram',
    address: 'Sector 14 Market Complex, Gurugram',
    contact_phone: '+91 124 408 1923',
    contact_email: 'support@ncrkarigar.in',
    type: 'Women Artisans & Facility',
    verification_status: 'VERIFIED',
    service_categories: ['Painting', 'Carpentry', 'Deep Cleaning'],
    commission_rate: 0.12,
    welfare_contribution_rate: 0.06,
    total_members: 36,
    total_jobs_completed: 189,
    welfare_fund_pool: 142000,
  },
];

export const MOCK_SERVICES: ServiceItem[] = [
  {
    id: 1,
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    category: 'Electrical',
    name: 'Short Circuit & Wiring Fault Repair',
    description: 'Diagnose and fix electrical tripping, MCB issues, burnt wiring, and switchboard failures.',
    pricing_model: 'FIXED',
    base_price: 399,
    estimated_duration_minutes: 60,
    emergency_multiplier: 1.5,
    required_skills: ['Wiring', 'Troubleshooting', 'Safety Compliance'],
  },
  {
    id: 2,
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    category: 'Electrical',
    name: 'Complete Switchboard & Inverter Setup',
    description: 'Installation and testing of modular switchboards, inverter backup connections, and earthing checks.',
    pricing_model: 'FIXED',
    base_price: 649,
    estimated_duration_minutes: 90,
    emergency_multiplier: 1.3,
    required_skills: ['Inverter Installation', 'Earthing', 'Load Balancing'],
  },
  {
    id: 3,
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    category: 'Plumbing',
    name: 'Pipe Leakage & Drainage Blockage Fix',
    description: 'High pressure clearing of choked kitchen/bathroom pipelines, PVC joint sealants, and tap replacements.',
    pricing_model: 'FIXED',
    base_price: 349,
    estimated_duration_minutes: 45,
    emergency_multiplier: 1.4,
    required_skills: ['Pipe Fitting', 'Drainage Cleansing', 'Pressure Testing'],
  },
  {
    id: 4,
    cooperative_id: 2,
    cooperative_name: 'Shramik Seva Cooperative Union',
    category: 'Plumbing',
    name: 'Water Tank Cleaning & Motor Pump Repair',
    description: 'Submersible water pump diagnosis, capacitor check, valve sealing, and motorized tank descaling.',
    pricing_model: 'FIXED',
    base_price: 799,
    estimated_duration_minutes: 120,
    emergency_multiplier: 1.4,
    required_skills: ['Pump Diagnostics', 'Plumbing Systems', 'Sanitization'],
  },
  {
    id: 5,
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    category: 'Carpentry',
    name: 'Door Lock, Hinge & Furniture Restoration',
    description: 'Precision latch fitting, wooden door realignment, concealed hinge restoration, and termite treatment.',
    pricing_model: 'FIXED',
    base_price: 499,
    estimated_duration_minutes: 75,
    emergency_multiplier: 1.2,
    required_skills: ['Joinery', 'Locksmithing', 'Finishing'],
  },
  {
    id: 6,
    cooperative_id: 3,
    cooperative_name: 'NCR Karigar Mahila Cooperative',
    category: 'Painting',
    name: 'Waterproofing & Wall Patching Solution',
    description: 'Efflorescence scraping, acrylic putty filling, primer application, and moisture barrier sealing.',
    pricing_model: 'SQUARE_FOOT',
    base_price: 850,
    estimated_duration_minutes: 180,
    emergency_multiplier: 1.2,
    required_skills: ['Surface Preparation', 'Putty Finishing', 'Waterproofing'],
  },
  {
    id: 7,
    cooperative_id: 2,
    cooperative_name: 'Shramik Seva Cooperative Union',
    category: 'HVAC / AC Repair',
    name: 'AC Gas Refill & Compressor Deep Jet Service',
    description: 'Coil jet chemical cleaning, pressure manifold gauge check, refrigerant top-up, and amp draw testing.',
    pricing_model: 'FIXED',
    base_price: 999,
    estimated_duration_minutes: 90,
    emergency_multiplier: 1.5,
    required_skills: ['Refrigeration', 'Electrical Safety', 'HVAC Maintenance'],
  },
];

export const MOCK_WORKERS: WorkerItem[] = [
  {
    id: 1,
    user_id: 2,
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    name: 'Ramesh Kumar Verma',
    phone: '+91 98101 23456',
    photo_url: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
    skills: ['Wiring', 'Troubleshooting', 'Safety Compliance', 'Inverter Installation'],
    experience_years: 9,
    certificates: [
      { name: 'ITI Electrician National Trade Certificate (NTC)', issuer: 'NCVT', year: 2016 },
      { name: 'Wireman License Grade A', issuer: 'Delhi Electrical Licensing Board', year: 2018 }
    ],
    verification_status: 'VERIFIED',
    verification_ref_id: 'DL-POL-2024-8832',
    rating: 4.9,
    total_jobs: 142,
    weekly_jobs_count: 3,
    reliability_score: 96.5,
    availability_status: 'AVAILABLE',
    latitude: 28.6250,
    longitude: 77.2150,
    address: 'Rajendra Nagar, New Delhi',
    welfare_status: 'ACTIVE_COVERED',
    total_earnings: 48600,
    welfare_balance: 14200,
  },
  {
    id: 2,
    user_id: 5,
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    name: 'Suresh Chandra Sharma',
    phone: '+91 98112 34567',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    skills: ['Pipe Fitting', 'Drainage Cleansing', 'Pressure Testing', 'Pump Diagnostics'],
    experience_years: 7,
    certificates: [
      { name: 'Certified Sanitary Plumber', issuer: 'National Skill Development Corp (NSDC)', year: 2018 }
    ],
    verification_status: 'VERIFIED',
    verification_ref_id: 'DL-POL-2024-9104',
    rating: 4.8,
    total_jobs: 118,
    weekly_jobs_count: 5,
    reliability_score: 94.0,
    availability_status: 'AVAILABLE',
    latitude: 28.6380,
    longitude: 77.2090,
    address: 'Pahar Ganj, New Delhi',
    welfare_status: 'ACTIVE_COVERED',
    total_earnings: 39200,
    welfare_balance: 11800,
  },
  {
    id: 3,
    user_id: 6,
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    name: 'Mohd. Imran Qureshi',
    phone: '+91 98188 45678',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    skills: ['Joinery', 'Locksmithing', 'Finishing'],
    experience_years: 11,
    certificates: [
      { name: 'Master Carpenter Guild Level 3', issuer: 'Delhi Board of Technical Education', year: 2014 }
    ],
    verification_status: 'VERIFIED',
    verification_ref_id: 'DL-POL-2023-7421',
    rating: 4.95,
    total_jobs: 184,
    weekly_jobs_count: 2,
    reliability_score: 98.2,
    availability_status: 'AVAILABLE',
    latitude: 28.6110,
    longitude: 77.2280,
    address: 'Daryaganj, Old Delhi',
    welfare_status: 'ACTIVE_COVERED',
    total_earnings: 62400,
    welfare_balance: 18400,
  },
  {
    id: 4,
    user_id: 7,
    cooperative_id: 2,
    cooperative_name: 'Shramik Seva Cooperative Union',
    name: 'Anita Devi Mahato',
    phone: '+91 98711 56789',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    skills: ['Surface Preparation', 'Putty Finishing', 'Waterproofing'],
    experience_years: 6,
    certificates: [
      { name: 'Professional Wall Coating Certification', issuer: 'Asian Paints Colour Academy', year: 2019 }
    ],
    verification_status: 'VERIFIED',
    verification_ref_id: 'DL-POL-2024-6012',
    rating: 4.85,
    total_jobs: 92,
    weekly_jobs_count: 1,
    reliability_score: 95.8,
    availability_status: 'AVAILABLE',
    latitude: 28.5244,
    longitude: 77.2066,
    address: 'Saket, New Delhi',
    welfare_status: 'ACTIVE_COVERED',
    total_earnings: 31000,
    welfare_balance: 9200,
  },
];

export const MOCK_JOBS: JobItem[] = [
  {
    id: 101,
    booking_ref: 'KS-JOB-2026-0891',
    customer_id: 3,
    customer_name: 'Vikram Malhotra',
    customer_phone: '+91 98111 22334',
    service_id: 1,
    service_name: 'Short Circuit & Wiring Fault Repair',
    service_category: 'Electrical',
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    assigned_worker_id: 1,
    assigned_worker_name: 'Ramesh Kumar Verma',
    assigned_worker_phone: '+91 98101 23456',
    status: 'IN_PROGRESS',
    slot_start: new Date(Date.now() - 3600000).toISOString(),
    slot_end: new Date(Date.now() + 7200000).toISOString(),
    address: 'C-42, Defence Colony, New Delhi',
    latitude: 28.5729,
    longitude: 77.2304,
    is_emergency: true,
    price_estimate: 648.5,
    payment_status: 'PAID',
    payment_method: 'UPI',
    customer_notes: 'Main power supply tripping continuously when AC starts.',
    supervisor_verified: true,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 102,
    booking_ref: 'KS-JOB-2026-0892',
    customer_id: 3,
    customer_name: 'Vikram Malhotra',
    customer_phone: '+91 98111 22334',
    service_id: 3,
    service_name: 'Pipe Leakage & Drainage Blockage Fix',
    service_category: 'Plumbing',
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    assigned_worker_id: 2,
    assigned_worker_name: 'Suresh Chandra Sharma',
    assigned_worker_phone: '+91 98112 34567',
    status: 'ASSIGNED',
    slot_start: new Date(Date.now() + 86400000).toISOString(),
    slot_end: new Date(Date.now() + 90000000).toISOString(),
    address: 'Tower 4, Flat 602, Commonwealth Games Village, New Delhi',
    latitude: 28.6189,
    longitude: 77.2801,
    is_emergency: false,
    price_estimate: 399.0,
    payment_status: 'PENDING',
    payment_method: 'CASH_ON_DELIVERY',
    customer_notes: 'Severe seepage under kitchen sink.',
    supervisor_verified: false,
    created_at: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 103,
    booking_ref: 'KS-JOB-2026-0893',
    customer_id: 4,
    customer_name: 'Sunita Mehra',
    customer_phone: '+91 98115 67890',
    service_id: 5,
    service_name: 'Door Lock, Hinge & Furniture Restoration',
    service_category: 'Carpentry',
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    status: 'REQUESTED',
    slot_start: new Date(Date.now() + 172800000).toISOString(),
    slot_end: new Date(Date.now() + 176400000).toISOString(),
    address: 'B-12, Green Park Extension, New Delhi',
    latitude: 28.5583,
    longitude: 77.2023,
    is_emergency: false,
    price_estimate: 549.0,
    payment_status: 'PENDING',
    payment_method: 'UPI',
    customer_notes: 'Teak main entrance door latch jammed.',
    supervisor_verified: false,
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const MOCK_ALLOCATION_EVALUATION: AllocationEvaluation = {
  job_id: 103,
  booking_ref: 'KS-JOB-2026-0893',
  service_name: 'Door Lock, Hinge & Furniture Restoration',
  service_category: 'Carpentry',
  total_eligible_workers: 4,
  recommended_worker_id: 3,
  recommended_worker_name: 3,
  top_recommendation_reason: 'Optimal composite score (93.4/100). Holds Grade 3 master joinery license, closest proximity (4.2 km), high 98.2% reliability rating, and low weekly allocations (2 jobs) ensuring income equalization.',
  candidates: [
    {
      worker_id: 3,
      worker_name: 'Mohd. Imran Qureshi',
      worker_phone: '+91 98188 45678',
      photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      rating: 4.95,
      verification_status: 'VERIFIED (DL-POL-2023-7421)',
      distance_km: 4.2,
      weekly_jobs: 2,
      scores: {
        skill_score: 30.0,
        availability_score: 20.0,
        distance_score: 13.8,
        reliability_score: 14.7,
        workload_score: 9.2,
        fairness_score: 9.5,
        total_score: 97.2,
      },
      narrative_explanation: 'Strongest technical match. 100% skill match on Joinery & Locksmithing. Proximity 4.2 km. Highest fairness equalization boost due to low weekly job volume.',
    },
    {
      worker_id: 1,
      worker_name: 'Ramesh Kumar Verma',
      worker_phone: '+91 98101 23456',
      photo_url: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
      rating: 4.9,
      verification_status: 'VERIFIED (DL-POL-2024-8832)',
      distance_km: 6.8,
      weekly_jobs: 3,
      scores: {
        skill_score: 24.0,
        availability_score: 20.0,
        distance_score: 11.2,
        reliability_score: 14.5,
        workload_score: 8.5,
        fairness_score: 8.0,
        total_score: 86.2,
      },
      narrative_explanation: 'Secondary match. Excellent track record and reliability, but primary trade is Electrical. Secondary carpentry skill verified.',
    },
  ],
};

export const MOCK_FORECAST: ForecastResponse = {
  zone: 'Central Delhi',
  service_category: 'Plumbing',
  current_active_workers: 18,
  total_projected_demand_7d: 146,
  capacity_status: 'DEFICIT',
  projected_utilization_pct: 115.8,
  recommendation: 'Impending trade deficit of 6 skilled plumbers over the next 5 days. Recommend activating off-duty standby roster and inviting cross-cooperative roster sharing.',
  daily_forecast: [
    { date: 'Mon', predicted_demand: 19, confidence_low: 16, confidence_high: 22, seasonal_factor: 1.12 },
    { date: 'Tue', predicted_demand: 21, confidence_low: 18, confidence_high: 25, seasonal_factor: 1.18 },
    { date: 'Wed', predicted_demand: 24, confidence_low: 20, confidence_high: 28, seasonal_factor: 1.25 },
    { date: 'Thu', predicted_demand: 22, confidence_low: 19, confidence_high: 26, seasonal_factor: 1.20 },
    { date: 'Fri', predicted_demand: 26, confidence_low: 22, confidence_high: 30, seasonal_factor: 1.34 },
    { date: 'Sat', predicted_demand: 32, confidence_low: 27, confidence_high: 37, seasonal_factor: 1.55 },
    { date: 'Sun', predicted_demand: 28, confidence_low: 23, confidence_high: 33, seasonal_factor: 1.40 },
  ],
};

export const MOCK_PROJECTS: InstitutionalProject[] = [
  {
    id: 1,
    client_name: 'Central Public Works Department (CPWD)',
    title: 'Nirman Bhawan Multi-Wing Electrical & HVAC Maintenance',
    description: 'Quarterly institutional overhaul of high-tension distribution boards, HVAC air handling units, and emergency power failovers.',
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    supervisor_id: 4,
    supervisor_name: 'Rajesh Tyagi (Govt. Licensed Inspector)',
    required_headcount: 14,
    skills_breakdown: { 'Industrial Electrician': 8, 'HVAC Technician': 4, 'Safety Supervisor': 2 },
    assigned_workers: [1, 2, 3],
    start_date: '2026-03-01',
    end_date: '2026-04-15',
    budget: 450000,
    amount_disbursed: 225000,
    status: 'IN_PROGRESS',
    progress_percentage: 65,
    milestones: [
      { title: 'Site Inspection & Safety Clearance', completed: true },
      { title: 'Wing A & B HT Panel Overhaul', completed: true },
      { title: 'HVAC Air Filter Replacement & Jet Cleaning', completed: true },
      { title: 'Final Supervisor Compliance Sign-Off', completed: false },
    ],
  },
  {
    id: 2,
    client_name: 'Delhi Metro Rail Corporation (DMRC)',
    title: 'Rajiv Chowk Metro Concourse Plumbing & Drainage Refurbishment',
    description: 'High-traffic commercial toilet refurbishment, heavy duty PRV valve installations, and grease trap servicing.',
    cooperative_id: 1,
    cooperative_name: 'Delhi Labour & Construction Cooperative Society',
    supervisor_id: 4,
    supervisor_name: 'Rajesh Tyagi (Govt. Licensed Inspector)',
    required_headcount: 10,
    skills_breakdown: { 'Senior Plumber': 6, 'Pipe Fitter': 4 },
    assigned_workers: [2],
    start_date: '2026-03-10',
    end_date: '2026-03-25',
    budget: 280000,
    amount_disbursed: 140000,
    status: 'IN_PROGRESS',
    progress_percentage: 45,
    milestones: [
      { title: 'Overnight Pressure Isolation & Choke Removal', completed: true },
      { title: 'PRV Valve Array Replaced', completed: true },
      { title: 'Automated Flush Valve Retrofitting', completed: false },
    ],
  },
];
